// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwgQAhIdx8aHbOmKyRKsYUaoS9CstpNhc',
    appId: '1:591592724316:web:99fb72d6a1788d75245399',
    messagingSenderId: '591592724316',
    projectId: 'ecommerceapp-fb6f1',
    authDomain: 'ecommerceapp-fb6f1.firebaseapp.com',
    storageBucket: 'ecommerceapp-fb6f1.appspot.com',
    measurementId: 'G-KBN7YZ355M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvUNxh9r2-YT9Bcy78jO9WH9T3jFfUZpg',
    appId: '1:591592724316:android:3e3b1f82a3122429245399',
    messagingSenderId: '591592724316',
    projectId: 'ecommerceapp-fb6f1',
    storageBucket: 'ecommerceapp-fb6f1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAc6Ig1EkR1fF_tyjtreBdOj8q-hhodKuw',
    appId: '1:591592724316:ios:371474c0746908cb245399',
    messagingSenderId: '591592724316',
    projectId: 'ecommerceapp-fb6f1',
    storageBucket: 'ecommerceapp-fb6f1.appspot.com',
    androidClientId: '591592724316-o1294943fl6urfjmnjs57bfna76neg00.apps.googleusercontent.com',
    iosClientId: '591592724316-38tnq0cvf8cvbbnss9i4fnno7s1m09re.apps.googleusercontent.com',
    iosBundleId: 'com.example.iStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAc6Ig1EkR1fF_tyjtreBdOj8q-hhodKuw',
    appId: '1:591592724316:ios:371474c0746908cb245399',
    messagingSenderId: '591592724316',
    projectId: 'ecommerceapp-fb6f1',
    storageBucket: 'ecommerceapp-fb6f1.appspot.com',
    androidClientId: '591592724316-o1294943fl6urfjmnjs57bfna76neg00.apps.googleusercontent.com',
    iosClientId: '591592724316-38tnq0cvf8cvbbnss9i4fnno7s1m09re.apps.googleusercontent.com',
    iosBundleId: 'com.example.iStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwgQAhIdx8aHbOmKyRKsYUaoS9CstpNhc',
    appId: '1:591592724316:web:0df239147cdd7762245399',
    messagingSenderId: '591592724316',
    projectId: 'ecommerceapp-fb6f1',
    authDomain: 'ecommerceapp-fb6f1.firebaseapp.com',
    storageBucket: 'ecommerceapp-fb6f1.appspot.com',
    measurementId: 'G-JMFXFL6G22',
  );

}